# Params for Orca nodes:

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

baro_filter_node:
  ros__parameters:
    use_sim_time: False
    ukf_Q: True

joy_linux_node:
  ros__parameters:
    use_sim_time: False
    dev: "/dev/input/js0"
    autorepeat_rate: 20.  # Set /joy Hz
    deadzone: 0.0  # Deadzone > 0 breaks autorepeat_rate

teleop_node:
  ros__parameters:
    use_sim_time: False
    stamp_msgs_with_current_time: True
    deadzone: 0.05  # Deadzone: ignore small joystick motions

    fcam: False
    lcam: False
    rcam: False
    show_window: True
    publish_h264: False
    show_slam_status: True
    show_slam_debug_image: True

    # vel_?_ should match in teleop_node and base_controller
    vel_x: 1.0
    vel_y: 0.5
    vel_z: 0.5
    vel_yaw: 1.0

base_controller:
  ros__parameters:
    use_sim_time: False
    stamp_msgs_with_current_time: True
    mdl_mass: 9.9
    mdl_volume: 0.01
    mdl_fluid_density: 997.0
    mdl_thrust_scale: 1.0
    publish_tf: True  # Publish odom->base_link

    # vel_?_ should match in teleop_node and base_controller
    x_vel: 1.0
    y_vel: 0.5
    z_vel: 0.5
    yaw_vel: 1.0

    x_accel: 1.0
    y_accel: 0.5
    z_accel: 0.5
    yaw_accel: 1.0

# Params for fiducial_vlam nodes:

vmap_main:
  ros__parameters:
    use_sim_time: False

    # Publish marker /tf
    publish_tfs: 1

    # Use a pre-built map
    make_not_use_map: 0

    # Load map
    marker_map_load_full_filename: "placeholder"

    # Don't save the map
    marker_map_save_full_filename: ""

    # Marker length
    marker_length: 0.1778

forward_camera/vloc_main:
  ros__parameters:
    use_sim_time: False
    stamp_msgs_with_current_time: 1 # Int can't be modified by param_rewrites? Hand-edit

    camera_frame_id: "forward_camera_frame"

    # Publish various things
    publish_camera_pose: 1
    publish_base_pose: 0
    publish_tfs: 0
    publish_tfs_per_marker: 0
    publish_camera_odom: 0
    publish_base_odom: 0
    publish_image_marked: 1

    # Gazebo 11 camera plugin publishes both camera info and images best-effort
    # May need to be modified for a real camera
    sub_camera_info_best_effort_not_reliable: 1
    sub_image_raw_best_effort_not_reliable: 1

    # OpenCV4 ArUco corner refinement
    # 0 = CORNER_REFINE_NONE
    # 1 = CORNER_REFINE_SUBPIX
    # 2 = CORNER_REFINE_CONTOUR (default)
    # 3 = CORNER_REFINE_APRILTAG (best and slowest)
    corner_refinement_method: 3

fiducial_localizer:
  ros__parameters:
    use_sim_time: False
    camera_frame_id: "forward_camera_frame"
    publish_rate: 20
    good_pose_distance: 2.0

# Params for orb_slam2 nodes:

orb_slam2_stereo:
  ros__parameters:
    use_sim_time: False

    # Gazebo 11 camera plugin publishes both camera info and images best-effort
    # May need to be modified for real cameras
    subscribe_best_effort: True

    publish_pointcloud: True
    publish_pose: True
    publish_tf: False
    localize_only: False
    reset_map: False

    load_map: False
    map_file: map.bin

    pointcloud_frame_id: map
    camera_frame_id: camera_frame  # TODO
    min_num_kf_in_map: 5

    ORBextractor/nFeatures: 1200
    ORBextractor/scaleFactor: 1.2
    ORBextractor/nLevels: 8
    ORBextractor/iniThFAST: 20
    ORBextractor/minThFAST: 7

    camera_fps: 20
    # Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
    camera_rgb_encoding: True

    # See https://github.com/raulmur/ORB_SLAM2/issues/89 for the author's explanation of these:
    ThDepth: 40.0
    depth_map_factor: 1.0
    camera_baseline: 171.0  # Right camera info p[3], flip sign

orb_slam2_localizer:
  ros__parameters:
    use_sim_time: False
    camera_frame_id: "left_camera_link"  # Note: the link, not the frame
    publish_rate: 20
    transform_expiration_ms: 0
