teleop_node:
  ros__parameters:
    axis_linear:
      x: 1  # Left thumb stick vertical
      y: 3  # Right thumb stick horizontal
      z: 4  # Right thumb stick vertical
    scale_linear:
      x: 1.0
      y: 0.5
      z: 0.5
    scale_linear_turbo:
      x: 1.0
      y: 0.5
      z: 0.5

    axis_angular:
      yaw: 0  # Left thumb stick horizontal
    scale_angular:
      yaw: 0.7
    scale_angular_turbo:
      yaw: 0.7

    enable_button: 4  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
